# Generated by Django 4.2.7 on 2025-08-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name='Номер телефона'
            ),
        ),
    ]
