# Generated by Django 4.2.7 on 2025-08-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_clients', 'Can view all clients')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
