# Generated by Django 4.2.7 on 2025-08-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_mailings', 'Can view all mailings'), ('can_disable_mailings', 'Can disable mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject'], 'permissions': [('can_view_all_messages', 'Can view all messages')], 'verbose_name': 'Сообщение (шаблон)', 'verbose_name_plural': 'Сообщения (шаблоны)'},
        ),
    ]
